import { MonsterCard } from "./models";


export const DUMMY_MONSTER_CARDS: MonsterCard[] = [
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 89631139,
    name: 'Blue-Eyes White Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.',
    race: 'Dragon',
    archetype: 'Blue-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/blue-eyes-white-dragon-89631139',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-001',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 5.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/89631139.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/89631139.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/89631139.jpg',
    },
    prices: {
      cardMarketPrice: 10.00,
      tcgPlayerPrice: 20.00,
      ebayPrice: 50.00,
      amazonPrice: 100.00,
      coolStuffIncPrice: 15.00,
    },
    attack: 3000,
    defense: 2500,
    level: 8,
    attribute: 'LIGHT',
  },
  {
    id: 46986414,
    name: 'Dark Magician',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'The ultimate wizard in terms of attack and defense.',
    race: 'Spellcaster',
    archetype: 'Dark Magician',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/dark-magician-46986414',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-005',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 7.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/46986414.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/46986414.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/46986414.jpg',
    },
    prices: {
      cardMarketPrice: 12.00,
      tcgPlayerPrice: 25.00,
      ebayPrice: 60.00,
      amazonPrice: 90.00,
      coolStuffIncPrice: 18.00,
    },
    attack: 2500,
    defense: 2100,
    level: 7,
    attribute: 'DARK',
  },
  {
    id: 44519536,
    name: 'Red-Eyes Black Dragon',
    type: 'Monster Card',
    humanReadableCardType: 'Normal Monster',
    frameType: 'normal',
    description: 'A ferocious dragon with a deadly attack.',
    race: 'Dragon',
    archetype: 'Red-Eyes',
    ygoprodeckUrl: 'https://ygoprodeck.com/card/red-eyes-black-dragon-44519536',
    sets: [
      {
        name: 'Legend of Blue Eyes White Dragon',
        code: 'LOB-070',
        rarity: 'Ultra Rare',
        rarityCode: '(UR)',
        price: 6.00,
      },
    ],
    imageLinks: {
      imageUrl: 'https://images.ygoprodeck.com/images/cards/44519536.jpg',
      imageUrlSmall: 'https://images.ygoprodeck.com/images/cards_small/44519536.jpg',
      imageUrlCropped: 'https://images.ygoprodeck.com/images/cards_cropped/44519536.jpg',
    },
    prices: {
      cardMarketPrice: 8.00,
      tcgPlayerPrice: 18.00,
      ebayPrice: 40.00,
      amazonPrice: 75.00,
      coolStuffIncPrice: 12.00,
    },
    attack: 2400,
    defense: 2000,
    level: 7,
    attribute: 'DARK',
  },
  
];
